version: "3.9"

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env.local
    environment:
      APP_ENVIRONMENT: ${APP_ENVIRONMENT:-dev}
      APP_ALLOWED_ORIGINS: ${APP_ALLOWED_ORIGINS:-["http://localhost:5173", "http://localhost:8001"]}
    ports:
      - "8001:8001"
    volumes:
      - ./.cache:/app/.cache
    command: [
      "sh",
      "-c",
      "uvicorn app.main:app --host 0.0.0.0 --port 8001 --reload"
    ]
